name: Trigger auto deployment for contentstack-next

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/contentstack-next-AutoDeployTrigger-78a14b23-254b-42d4-915a-f1960ba96c16.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTENTSTACKNEXT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: cafb88bacb28acr.azurecr.io
          registryUsername: ${{ secrets.CONTENTSTACKNEXT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTENTSTACKNEXT_REGISTRY_PASSWORD }}
          containerAppName: contentstack-next
          resourceGroup: contentstack-containerapps
          imageToBuild: cafb88bacb28acr.azurecr.io/contentstack-next:${{ github.sha }}
          environmentVariables: >
            CONTENTSTACK_API_KEY=${{ secrets.CONTENTSTACK_API_KEY }}
            CONTENTSTACK_DELIVERY_TOKEN=${{ secrets.CONTENTSTACK_DELIVERY_TOKEN }}
            CONTENTSTACK_ENVIRONMENT=${{ secrets.CONTENTSTACK_ENVIRONMENT }}
            CONTENTSTACK_LIVE_PREVIEW=${{ secrets.CONTENTSTACK_LIVE_PREVIEW }}
            

     

